# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.

title: Ersu Labs
email: contact@ersulabs.com
description: "Deep learning from scratch. Mathematics and algorithmic implementations of ML models."
twitter_username: 
github_username: cemersu
minimal_mistakes_skin: dark
search: true
favicon: /assets/images/favicon.png
# URL Ayarı
url: "https://ersulabs.com"

# 1. MATEMATİK MOTORU AYARI (Kritik)
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: true

remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Istanbul

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# 2. PROFİL FOTOĞRAFI AYARI
# BURAYA DİKKAT: Dosya ismin GitHub'da tam olarak neyse (JPG, jpeg, png) aynısını yaz!
author:
  name: "Cem ERSU"
  avatar: "/assets/images/cem.jpg"
  bio: "Unboxing the Black Box. Deconstructing AI algorithms with Math & Python."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@ersulabs.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cemersu"

footer:
  links: []

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true # <-- İŞTE BU SATIR MATEMATİĞİ ZORLA AÇAR!
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# Google Analytics Ayarları
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-T3YS9NZNN8" # Buraya G- ile başlayan kodunu yapıştır
    anonymize_ip: true
